### ISSUE TITLE
Snakemake bug when contig header contains FASTA file name

### ISSUE THREAD

**Issue by CarraraAlessia** [metagenlab/MeSS#21]
Hi,

I noticed that the pipeline fails at rule 'compress_contig_fastqs' if the filename of my FASTA file is contained in the contig header. 
E.g. sample1.fna & >sample1_contig1

![mess_error](https://github.com/user-attachments/assets/70187421-36f5-4439-b47a-c5786bde99ed)

Thanks for fixing it or mentioning it in the documentation!

Cheers! :)))

**Comment by farchaab** [comment]
Hello Alessia !

Can you provide an example fasta and input table to reproduce your error ?

**Comment by CarraraAlessia** [comment]
Hi,
Here are the command and input files to reproduce the error:

_mess simulate -i simulate_test.csv  --fasta fasta/_

[simulate_test.csv](https://github.com/user-attachments/files/16760193/simulate_test.csv)
[NC.fna.gz](https://github.com/user-attachments/files/16760199/NC.fna.gz)
